apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ms-ingress
  labels:
    name: ms-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: msfrontend.inframellow.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: ms-service
            port: 
              number: 80
